(paragraph [
 ((sym "*" @bold.start) (sym "*" @bold.end) (#org-is-valid-markup-range? @bold.start @bold.end))
 ((sym "~" @code.start) (sym "~" @code.end) (#org-is-valid-markup-range? @code.start @code.end))
 ((sym "/" @italic.start) (sym "/" @italic.end) (#org-is-valid-markup-range? @italic.start @italic.end))
 ((sym "_" @underline.start) (sym "_" @underline.end) (#org-is-valid-markup-range? @underline.start @underline.end))
 ((sym "=" @verbatim.start) (sym "=" @verbatim.end) (#org-is-valid-markup-range? @verbatim.start @verbatim.end))
 ((sym "+" @strikethrough.start) (sym "+" @strikethrough.end) (#org-is-valid-markup-range? @strikethrough.start @strikethrough.end))
 ((sym "[" @hyperlink.start) (sym "]" @hyperlink.end) (#org-is-valid-hyperlink-range? @hyperlink.start @hyperlink.end))
 ; TODO: Check latex
 ; ((expr ("\\" @text.math.start.left "(" @text.math.start.right)) (expr ("\\" ")" @text.math.end)) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; (expr "\\" @text.math.start.left "(" @text.math.start.right "\\" ")" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; ((expr ("\\" @text.math.start.left ("str")+ @text.math.start.right "{")) (expr "}" @text.math.end) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; (expr "\\" @text.math.start.left ("str")+ @text.math.start.right "{" "}" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; (expr "\\" @text.math.start.left ("str")+ @text.math.start.right @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
])

(item [
 ((sym "*" @bold.start) (sym "*" @bold.end) (#org-is-valid-markup-range? @bold.start @bold.end))
 ((sym "~" @code.start) (sym "~" @code.end) (#org-is-valid-markup-range? @code.start @code.end))
 ((sym "/" @italic.start) (sym "/" @italic.end) (#org-is-valid-markup-range? @italic.start @italic.end))
 ((sym "_" @underline.start) (sym "_" @underline.end) (#org-is-valid-markup-range? @underline.start @underline.end))
 ((sym "=" @verbatim.start) (sym "=" @verbatim.end) (#org-is-valid-markup-range? @verbatim.start @verbatim.end))
 ((sym "+" @strikethrough.start) (sym "+" @strikethrough.end) (#org-is-valid-markup-range? @strikethrough.start @strikethrough.end))
 ((sym "[" @hyperlink.start) (sym "]" @hyperlink.end) (#org-is-valid-hyperlink-range? @hyperlink.start @hyperlink.end))
 ; TODO: Check latex
 ; ((expr ("\\" @text.math.start.left "(" @text.math.start.right)) (expr ("\\" ")" @text.math.end)) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; (expr "\\" @text.math.start.left "(" @text.math.start.right "\\" ")" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; ((expr ("\\" @text.math.start.left ("str")+ @text.math.start.right "{")) (expr "}" @text.math.end) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; (expr "\\" @text.math.start.left ("str")+ @text.math.start.right "{" "}" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; (expr "\\" @text.math.start.left ("str")+ @text.math.start.right @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
])

(cell (contents [
 ((sym "*" @bold.start) (sym "*" @bold.end) (#org-is-valid-markup-range? @bold.start @bold.end))
 ((sym "~" @code.start) (sym "~" @code.end) (#org-is-valid-markup-range? @code.start @code.end))
 ((sym "/" @italic.start) (sym "/" @italic.end) (#org-is-valid-markup-range? @italic.start @italic.end))
 ((sym "_" @underline.start) (sym "_" @underline.end) (#org-is-valid-markup-range? @underline.start @underline.end))
 ((sym "=" @verbatim.start) (sym "=" @verbatim.end) (#org-is-valid-markup-range? @verbatim.start @verbatim.end))
 ((sym "+" @strikethrough.start) (sym "+" @strikethrough.end) (#org-is-valid-markup-range? @strikethrough.start @strikethrough.end))
 ((sym "[" @hyperlink.start) (sym "]" @hyperlink.end) (#org-is-valid-hyperlink-range? @hyperlink.start @hyperlink.end))
 ; TODO: Check latex
 ; ((expr ("\\" @text.math.start.left "(" @text.math.start.right)) (expr ("\\" ")" @text.math.end)) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; (expr "\\" @text.math.start.left "(" @text.math.start.right "\\" ")" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; ((expr ("\\" @text.math.start.left ("str")+ @text.math.start.right "{")) (expr "}" @text.math.end) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; (expr "\\" @text.math.start.left ("str")+ @text.math.start.right "{" "}" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; (expr "\\" @text.math.start.left ("str")+ @text.math.start.right @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
]))

(drawer (contents [
 ((sym "*" @bold.start) (sym "*" @bold.end) (#org-is-valid-markup-range? @bold.start @bold.end))
 ((sym "~" @code.start) (sym "~" @code.end) (#org-is-valid-markup-range? @code.start @code.end))
 ((sym "/" @italic.start) (sym "/" @italic.end) (#org-is-valid-markup-range? @italic.start @italic.end))
 ((sym "_" @underline.start) (sym "_" @underline.end) (#org-is-valid-markup-range? @underline.start @underline.end))
 ((sym "=" @verbatim.start) (sym "=" @verbatim.end) (#org-is-valid-markup-range? @verbatim.start @verbatim.end))
 ((sym "+" @strikethrough.start) (sym "+" @strikethrough.end) (#org-is-valid-markup-range? @strikethrough.start @strikethrough.end))
 ((sym "[" @hyperlink.start) (sym "]" @hyperlink.end) (#org-is-valid-hyperlink-range? @hyperlink.start @hyperlink.end))
 ; TODO: Check latex
 ; ((expr ("\\" @text.math.start.left "(" @text.math.start.right)) (expr ("\\" ")" @text.math.end)) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; (expr "\\" @text.math.start.left "(" @text.math.start.right "\\" ")" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; ((expr ("\\" @text.math.start.left ("str")+ @text.math.start.right "{")) (expr "}" @text.math.end) (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; (expr "\\" @text.math.start.left ("str")+ @text.math.start.right "{" "}" @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
 ; (expr "\\" @text.math.start.left ("str")+ @text.math.start.right @text.math.end (#org-is-valid-latex-range? @text.math.start.left @text.math.start.right @text.math.end))
]))
