name: docgen

on:
  push:
    branches:
      - master

jobs:
  docgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        id: neovim
        with:
          neovim: true
          version: v0.9.5
      - name: Install lemmy-help
        run: |
          curl -Lq https://github.com/numToStr/lemmy-help/releases/latest/download/lemmy-help-x86_64-unknown-linux-gnu.tar.gz | tar xz
          echo "$PWD" >> $GITHUB_PATH
      - name: Generate api docs
        run: make api_docs
      - name: Generate vim docs
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: orgmode
          pandoc: 'DOCS.md'
      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MSG: |
            [docgen] Update docs
        run: |
          rm lemmy-help
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add doc/orgmode.txt
          git add doc/orgmode_api.txt
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push)
