name: dev

on:
  push:
    branches:
      - master
  pull_request: # Luarocks upload only tests installation

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  luarocks_dev:
    needs: tests
    uses: ./.github/workflows/luarocks.yml
    with:
      luarocks_version: dev
