name: Push release to Luarocks

on:
  push:
    tags:
      - '*'
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  version:
    needs: tests
    runs-on: ubuntu-latest
    outputs:
      luarocks_version: ${{ steps.get_version.outputs.LUAROCKS_VERSION }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required to count the commits
    - name: Get Version
      id: get_version
      run: echo "LUAROCKS_VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT
  luarocks:
    needs: version
    uses: ./.github/workflows/luarocks.yml
    with:
      luarocks_version: ${{ needs.version.outputs.luarocks_version }}
