name: tests

on:
  workflow_call:

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
            # CLI arguments
          args: --check lua/ tests/
  tests:
    strategy:
      fail-fast: false
      matrix:
        version:
          - v0.9.5
          - v0.10.0
          - v0.10.1
          - nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        id: neovim
        with:
          neovim: true
          version: ${{ matrix.version }}
      - name: Run tests
        run: make test
